name: 'Send Pushover Notification'
description: 'Send a notification via Pushover API'
inputs:
  pushover_api_token:
    description: 'Pushover API token'
    required: true
  pushover_user_key:
    description: 'Pushover user key'
    required: true
  title:
    description: 'Notification title'
    required: true
  message:
    description: 'Notification message'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Send Pushover notification
      shell: bash
      run: |
        curl -Ss -X POST -H 'Content-type: application/json' \
          --data '{
            "token": "${{ inputs.pushover_api_token }}",
            "user": "${{ inputs.pushover_user_key }}",
            "title": "${{ inputs.title }}",
            "message": "${{ inputs.message }}"
          }' \
          https://api.pushover.net/1/messages.json
